name: Release AppImage

on:
  push:
    tags:
      - 'v*'  # Trigger on any tag starting with 'v'

# Add permissions block
permissions:
  contents: write  # Needed for creating releases and uploading assets

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v4
    
    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y python3-pip python3-venv imagemagick-6.q16 appstream
        # Fix ImageMagick policy and create magick symlink
        sudo sed -i 's/rights="none" pattern="PDF"/rights="read|write" pattern="PDF"/' /etc/ImageMagick-6/policy.xml
        sudo ln -s /usr/bin/convert /usr/local/bin/magick
        # Validate AppStream metadata
        appstreamcli validate "$GITHUB_WORKSPACE/build/metainfo/io.github.sodomak.vcam-bg.metainfo.xml"
    
    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.12'
    
    - name: Get version
      id: get_version
      run: |
        VERSION=$(grep -oP 'VERSION = "\K[^"]+' src/version.py)
        echo "version=$VERSION" >> $GITHUB_OUTPUT
    
    - name: Build AppImage
      run: |
        chmod +x build/create-appimage.sh
        ./build/create-appimage.sh
    
    - name: Create Release
      id: create_release
      uses: softprops/action-gh-release@v1
      with:
        name: Release ${{ steps.get_version.outputs.version }}
        draft: false
        prerelease: false
        files: |
          vcam-bg-x86_64.AppImage
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
